services:
    alfresco:
        build:
            context: .
        depends_on: 
          postgres:
            condition: service_healthy
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 3gb
            reservations:
              cpus: '1'
              memory: 2gb
        ports:
            - "8080:8080"
    postgres:
        image: postgres:14.4
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
            - PGUSER=alfresco
        command: >-
            postgres
              -c max_connections=200
              -c logging_collector=on
              -c log_min_messages=LOG
              -c log_directory=/var/log/postgresql
        healthcheck:
          test: ["CMD", "pg_isready"]
          interval: 10s
          timeout: 5s
          retries: 5
        deploy:
          resources:
            limits:
              cpus: '1'
              memory: 1gb
            reservations:
              cpus: '0.5'
              memory: 512m          