services:
  alfresco:
    image: alfresco/alfresco-content-repository-community:23.2.1
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dindex.subsystem.name=solr6
        -Dsolr.host=solr6
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Drepo.event2.enabled=false
        -Dmessaging.subsystem.autoStart=false        
        -Dcsrf.filter.enabled=false
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: "alfresco"
      POSTGRES_USER: "alfresco"
      POSTGRES_DB: "alfresco"
    command: postgres -c max_connections=300 -c log_min_messages=LOG

  solr6:
    image: alfresco/alfresco-search-services:2.0.11
    environment:
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco"
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: >-
          -Dalfresco.secureComms.secret=secret

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:5.1.3
